#!/bin/python3
import string
import random

# Generate a random password suggestion using uppercase, lowercase, punctuation, and digits.
# A 20-character password is generated by sampling from the combined pool.
pass_suggest = string.ascii_uppercase + string.ascii_lowercase + string.punctuation + string.digits
pass_suggest = "".join(random.sample(pass_suggest, 20))
print(f"Password suggestion: {pass_suggest}")

# Initialize variables to check the presence of uppercase, lowercase, digits, and punctuation in the user-inputted password.
upp = low = dig = pun = 0

# Prompt user for a password input (up to 20 characters).
password = input("Enter Password up to 20 characters: ")

# Check each character in the password to identify if it contains uppercase, lowercase, digits, or punctuation.
for i in password:
    if i in string.ascii_uppercase:
        upp = 1
    if i in string.ascii_lowercase:
        low = 1
    if i in string.punctuation:
        pun = 1
    if i in string.digits:
        dig = 1

# Check if the entered password is a common password (listed in 'common_pass.txt').
with open('common_pass.txt', 'r') as f:
    common = f.read().splitlines()  # Read and split the common passwords file into a list.
    
# If the password is found in the common password list, prompt the user to choose another password.
if password in common:
    print("The password is common, use another password")
    exit()

# Get the length of the password.
passlen = len(password)

# Evaluate the password strength based on its length and the combination of character types.
if passlen < 20:
    # If the password contains at least three types (uppercase, lowercase, digits, punctuation)
    if (upp + low + dig + pun) > 3:
        if passlen < 9:
            print("Password is okay!!")
        elif passlen < 13:
            print("Password is decent!!")
        elif passlen < 17:
            print("Password is strong!!")
        else:
            print("Password is almost unbreakable")
    else:
        print("Password is weak, use uppercases, lowercases, digits, and special characters")
else:
    print("Password length exceeds 20 characters")
